#ifndef SOURCE_API_TOKENS_H
#define SOURCE_API_TOKENS_H

#define SHARED_SERVER_URL "http://dr-tinder.herokuapp.com"
//#define SHARED_SERVER_URL "http://localhost:5000"
#define SHARED_SERVER_USERS_SUB_URL "users"
#define SHARED_SERVER_PHOTO_SUB_URL "photo"
#define SHARED_SERVER_INTERESTS_SUB_URL "interests"

#define USERS_TOKEN "users"

#define USER_TOKEN "user"
#define USER_ID_TOKEN "id"
#define USER_NAME_TOKEN "name"
#define USER_ALIAS_TOKEN "alias"
#define USER_EMAIL_TOKEN "email"
#define USER_PHOTO_TOKEN "photo_profile"
#define USER_UPDATE_PHOTO_TOKEN "photo"

#define INTERESTS_TOKEN "interests"

#define INTEREST_TOKEN "interest"
#define INTEREST_CATEGORY_TOKEN "category"
#define INTEREST_VALUE_TOKEN "value"

#define LOCATION_TOKEN "location"
#define LOCATION_LATITUDE_TOKEN "latitude"
#define LOCATION_LONGITUDE_TOKEN "longitude"

#define METADATA_TOKEN "metadata"
#define METADATA_VERSION_TOKEN "version"
#define METADATA_COUNT_TOKEN "count"

#define INTEREST_ARRAY {INTEREST_TOKEN, INTEREST_CATEGORY_TOKEN, INTEREST_VALUE_TOKEN}
#define INTERESTS_ARRAY {INTERESTS_TOKEN, INTEREST_CATEGORY_TOKEN, INTEREST_VALUE_TOKEN}
#define LOCATION_ARRAY {LOCATION_TOKEN, LOCATION_LATITUDE_TOKEN, LOCATION_LONGITUDE_TOKEN}
#define METADATA_ARRAY {METADATA_TOKEN, METADATA_VERSION_TOKEN, METADATA_COUNT_TOKEN}
#define USERS_ARRAY {USERS_TOKEN, USER_TOKEN}
#define USER_ARRAY {USER_TOKEN, USER_ID_TOKEN, USER_NAME_TOKEN, USER_ALIAS_TOKEN, USER_EMAIL_TOKEN, USER_PHOTO_TOKEN, INTERESTS_TOKEN, LOCATION_TOKEN}

#endif //SOURCE_API_TOKENS_H
