#No modificar
notifications:
  slack:
    rooms:
      - taller2-drv:p0qCWhuViwNDcP2vT6DjS8Qv#talk-to-travis
      - taller2-drv:p0qCWhuViwNDcP2vT6DjS8Qv#general-build-status
#############

language: c

compiler: gcc

script: 
 - echo "OK"
 - echo "OK"
 - echo "OK"
