#Slack integration
notifications:
  slack:
    rooms:       
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#talk-to-travis
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#general-build-status
#Branch specific          
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#android-app
    email: false
##############################

language: android

android:
  components:
    -android-21

script:
- echo "OK"
- echo "OK"
- echo "OK"
