#Slack integration
notifications:
  slack:
    rooms:       
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#talk-to-travis
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#general-build-status
    email: false
##############################

language: c

compiler: gcc

script:
  - gcc -coverage -O0 hello.c -o hello
  - ./hello
  - gcov hello.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
