#Slack integration
notifications:
  slack:
    rooms:       
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#talk-to-travis
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#general-build-status
#Branch specific          
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#shared-server
    email: false
##############################

language: node_js

node_js:
   - "0.8"

before_install: npm install -g grunt-cli

install: npm install

before_script: grunt build

script:
  - echo "hello"

after_success:
  - bash <(curl -s https://codecov.io/bash)
