#Slack integration
notifications:
  slack:
    rooms:
          #General
          secure: F7BQ1oTXdb2o6jeREgSWqAqCY7KATRl4pkhacjHCyab+e1r/HelXtWSaqJQ0knM1UT8OJ0evg3G8lmvcDkIuUmiuLf3PBEDCeQtGMDa4E1+wwNEQG5O9r+M+CI1XI8kK26BxRZXKv9RuvauOoG60QhpxmK/WK9X2EtceG7pZut0dS7O7Ew9Qk/rJ/Tcn5GedgmM8JfFCk+aGjsVRe8HmJf6zB1WyXlohMVxPyz7uF8m1gBjSkoJWbY2RELuv5zKwAQid4/zE4aILR0lxfhOz6tMaD05x56I/y4ml+hMVO7qkuxNooeTYbjVFh/g1qPoqXdcrlQa6IZULkMGb4DofIjSuFGbrdaiUPhAxhvPEfbNHJmJmbejFYp1zSvYmUDjxoDvob3MQcZaeZvLKkLCOO4wQOuFCfQtMqzA7qBveki9en/TX+CvyoMow0hyMNem5ba3ZXsxb0sZfco1CmUescfidzquXYTMZcyacjI17G6uQ4ZSCZUItCFxmRtG+C+ApWsPOVFWqYS3BneZ5e2rldSLuh9o3Yq+L11Vh//Y4a4WX60EMf4gup97m1cM9u9YpgvI49/Hts/PR0Ci9m0MiGUrXSbUOqbb8L/M3Ue1I+PQ1gvs0PBq7ZVPJv/SiPXAcRQTRAyFZMpdaJThL0bdhFbRQjamm1Q3A9CfF+MqOZRI=
          #Travis
          secure: sNATvEZVzJFXBYXATfknnWfMApF21/Wxn2a5ScFa2R5/3GyJqfKUH55j6gsOkL+X4TvoHSGeJSLdEd0VjvIk972RHzPrrg0Lp4vm/kqsX4LR+2TwhpY6iLJAOXRYQg1Vdbn4xRQOM9WQldgJkKYWavS7lZKvBUuLC+9R0QwV6bxteEV7BlN5yjts+GWJtolaDUjbwyan1Cotl+3B9AWNCQ/wIG4qt9L97xd1qQjEGWgh/5pSYUMtFH9tpnF4QZcjtMJLOKtmRJU3CiKZ33ulpR57+i2xgkH5LxNIinyy95qlH6a1DBNGGbYQbh9gAZ3GWUfwAtTKk0Y/PBeRSNrlM2PQYWXLHSfZ+WYh+EKbvCo/bNqcvBe+liE0ov2AwZAL6qAfRiJ4ugWZu5b1YjB/1md2NUVV8aDYIRBdN+xQDtGuxCmxFQRP9a6Xtu/vbJm1tBgPp9bogfNF2QGNIogtahV0IlzdaweP2Gz9c1qKd5N0cSRjkFJ8GG7P7H3NflwJvQew+BjMWczwGPg3l8IKIiAuT9YbIaBf59c1X+amfHVYR+Pt0pRjvGrGOUAX/WOj5AiokTBo63r2I72/jPrzFcBWvg6vmWA2i4EbOQ8Y/oI98Vfxabv40hQzSWz4GsoogSw59W6Ox1+ZmmOHrjmQ26oPKf6kjSOH/Khza2OpCbU=
          #Heroku
          secure: s7Rx5sjPaSbtrgaX1m9b/UXGhZBWXpRJKr7SjtVzXCAxeWimiXe3JAJL7cfEvzuq/WLoVRx1raSODGXdA+xe2Ig2ya+0vIURsZ54OIkmbFS2n+m1nkZD7kUsqvrsxWQY6RhlWABuAVVJpaqYA2v5iOBna7laGaOCmf7h3bdohHd/FNq6Nr5p/0gsv4KQrkf6ZwCAyM+WJzzcqJv39zGTDdiwiZm9sOjITqjNXPLW84pwjBrJboGDhFSN0pZ8O+KkFHtx3AoBcd7igcH3Od0CCDZju93HN5LALkdwC4u8T2hQN5aUTE7HiVbkogClJJaOHyIV6Fyn2Mg6KcjHPCnvBrOHsKip9V52csq6vsDNmdFIoCJlPBR4VoWf7frE2iZZd4AR9/ilPbpDB6ncD+nkXTTVxIxMcTPcZV26niESmC6aKppQ+fIPuq7chJlklvSEBYDJEUC1JS7ilksJBUrXdjipnk9FKCNdobWnIOSc5IAFQcy9fO6Uee5srgx6JMUFnab46VK6GEX2qPJqScPqLPX7Wej6r3QnqwO2p5S9VhJYdcbwRTQlA7fDqaeaDLWXvDwmwpLSeTOiYKtCuFJKV7JjMMou8MT3xVVyYmFJMIYC6xWMHNge8pgK+DT838HXtQ5RzO9ND7NdYEKo0tr0Du+0po0z1L3z84UsG2jLsm8=
    email: false
##############################

language: c

compiler: gcc

deploy:
  provider: heroku
  api_key:
    secure: PqH92l1gcf3DMlvyafgwCD4iWqZp7Yzs9XfNLPzAbwcp08fDRxDLNZB2+A+YzqRMTkEyZvvZSANmw1FlnJjeXKs5cLsSeWnNnJfsNY3mSRaRC3Ri5k/l8kwbNL4m+Jw++Mcf/g5a+MZiaMs0Z63OFWHdJCjY890ZSX3B8arXgGIXDPQqCTllFGxRJg1bKsHK5+6qbF8CcJv2Uz5olpkIoqwJVsKFVvE+wC3TD3EtrcxxfdbnxcjNlWXoEi7R8j0sp3lJhcGu3M6g++aZBRQ94A/uPmmwPyaK4toxU7b8TnuGXzeDhhm4ow2ABzBm+tLNk7GIgudLCZkSJjmOxw+TqAOObvTss0IDnH8I+1JglKn189oNvTDcB4fDLk40efZ5TMPExFpdIxLF9bzmTaD+JMleoLCwFjTyv95UOnSpAxR7AtaFWbY6X5gioz+afvVLUaktDw3zH8bGUTDRFZAd+8kcde4ViSUr7BdH109eQRHW3cE5c8azWBPu5dnsidA7OEDdBm1UDNb3de54GrS8jfeMnhHbFq2iUDHaaHO3DJ/aRIOhAUJNqTljPsCS/NI7PC/HLw+54OqeQ40VLINa6TngV5S9MJsoxDG+KBPc+aP0wCwwhq8d5X7O/JQEkt3xnH4INbWbyjzB7hS8kag/5/zX3FvFqK1W50V3eYGBGVE=
  app: dr-tinder
  on: master

script:
- echo "OK"
- echo "OK"
- echo "OK"
