#Slack integration
notifications:
  slack:
    rooms:
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#talk-to-travis
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#general-build-status
#Branch specific
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#app-server
    email: false
##############################

language: cpp

compiler: g++

sudo: required

services:
  - docker

before_install:	
  - docker build --no-cache -t docker-server-test .

script:
  - docker run docker-server-test
