#Slack integration
notifications:
  slack:
    rooms:
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#talk-to-travis
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#general-build-status
#Branch specific
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#app-server
    email: false
##############################

language: c

compiler: gcc

before_script:
  - sudo apt-get update
  - sudo apt-get install -y libgflags-dev libsnappy-dev libbz2-dev zlib1g-dev
  - git submodule init
  - git submodule update

script:
  - cd source/libs/rocksdb
  - make install
  - cd ../jsoncpp
  - python amalgamate.py
  - cd ../../Servidor
  - make MakefileServidor
  - cd ..
  - cd Cliente
  - make MakefileCliente

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash execute.sh
