#Slack integration
notifications:
  slack:
    rooms:       
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#talk-to-travis
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#general-build-status
#Branch specific          
          - taller2-drv:7KZQ9SbRYxKXS4XPARTY3Qjs#shared-server
    email: false
##############################

language: node_js

before_install: 
  - npm -g install npm@latest-2
  - npm install -g grunt-cli
  - npm install load-grunt-tasks

install: npm install

before_script: grunt test

script:
  - echo "hello"

after_success:
  - bash <(curl -s https://codecov.io/bash)
